services:
  db-gopoli:
    build: .
    image: ghcr.io/gopoli/gopoli-db:latest
    container_name: gopoli-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-gopoli}
      POSTGRES_USER: ${POSTGRES_USER:-gopoli}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gopoli}
    volumes:
      - gopoli_pgdata:/var/lib/postgresql/data

volumes:
  gopoli_pgdata:
